services:
  postgres:
    container_name: reddit_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: reddit
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data: